### ISSUE TITLE
Brazil data mistakes

### ISSUE THREAD

**Issue by Cunziria** [OxCGRT/covid-policy-tracker#17] opened 2020-06-06 14:59 UTC
There appears to be a mistake in processing Brazil's data on the API. The confirmed cases and deaths numbers bounce between a high and a low value.

For example, 2020-03-27 shows 2915 cases and 77 deaths, while the next day 2020-03-28 shows just 4 cases and 0 deaths. If only this were true.

This is also a problem for a few other values of countries, including Ecuador and Lithuania.

**Comment by TobyPhillips** [comment] 2020-06-06 16:54
Hi, can you you tell me how you are accessing the data. Is if one of the CSVs on this repo, or is it through the API? I can't see the issue you describe.

BRA on 2020-03-28 has 3417 cases and 92 deaths. We pull case and death numbers from Our World in Data who in turn compile reports from the European Centre for Disease Control. It may have been a temporary issue with their underlying data, but as I say, it doesn't seem to be there any more as far as I can tell.

**Comment by Cunziria** [comment] 2020-06-06 17:05
Here: https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/date-range/2020-01-02/2020-05-29
BRA on 2020-03-28 is still 4 confirmed and 0 deaths as far as I can see.

Thanks for your work on this dataset!

**Comment by TobyPhillips** [comment] 2020-06-07 15:14
Thanks, that's helpful. There does indeed seem to be a problem with the API. The CSVs in our data folder here are correct, though.

Could you please let me know any specific issues with other countries? At the moment, as far as we can tell, the problem is confined to Brazil. But it would be helpful to know specific other country/day combinations with problems.

**Comment by TobyPhillips** [comment] 2020-06-08 11:07
Thanks for that detailed table. The Brazil problem was a legitimate issue with our API where it was pulling data from state-level Brazilian entities rather than the national numbers (we are starting to pilot sub-national data collection, and still ironing out database kinks). This should be fixed now, but please let me know if you continue to see problems.

I did a few spot checks on the other countries in your table. These seem to be underlying variances in the data reported by the ECDC, as collated by Our World in Data: https://github.com/owid/covid-19-data/blob/master/public/data/ecdc/full_data.csv

Each day, the ECDC records how many cases a country says they have had up to that point. If a country reports less than the day before, the ECDC will faithfully reproduce this, and this is the variation you are picking up (at least from the few spot checks that I did – eg FRA 2020-06-03 and ESP 2020-04-19).

**Comment by Cunziria** [comment] 2020-06-08 18:05
Thanks, the Brazil data looks corrected now. There remain 14 entries where confirmed cases and/or deaths decrease, but these look like isolated cases - feeding through from the ECDC data as you explained - rather than systematic like Brazil's. The OWID dataset you linked to contains the same negative daily figures.

Thanks again for your valuable work!

For reference, the remaining anomalous entries are below, again from https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/date-range/2020-01-02/2020-06-07

|date       |country | confirmed| deaths| daily_cases| daily_deaths|
|:----------|:-------|---------:|------:|-----------:|------------:|
|2020-04-19 |ESP     |    193252|  20453|        -713|          410|
|2020-04-29 |LTU     |      1344|     44|        -105|            3|
|2020-05-03 |PRT     |     25190|   1023|        -161|           16|
|2020-05-07 |ECU     |     29420|   1618|       -2461|           49|
|2020-05-09 |ECU     |     28818|   1704|       -1480|           50|
|2020-05-11 |SMR     |       628|     41|          -9|            0|
|2020-05-12 |ECU     |     29509|   2145|         -50|           18|
|2020-05-20 |BEN     |       130|      2|        -209|            0|
|2020-05-21 |GBR     |    248293|  35704|        -525|          363|
|2020-05-21 |UGA     |       145|      0|        -115|            0|
|2020-05-25 |ESP     |    235400|  26834|        -372|        -1918|
|2020-06-02 |UGA     |       457|      0|          -1|            0|
|2020-06-03 |FRA     |    151325|  28940|        -766|          107|
|2020-06-03 |PAN     |     14095|    258|         258|          -86|

**Closed** 2020-06-08 18:05 UTC
